// SOME ACTIONS
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const LOADING_PRODUCTS = 'LOADING_PRODUCTS';
const SET_CURRENT_PRODUCT = 'SET_CURRENT_PRODUCT';
const FETCH_COMMENT = 'FETCH_COMMENT';
const CREATE_COMMENT = 'CREATE_COMMENT';
const FETCH_ADDRESS = 'FETCH_ADDRESS';

export {
  FETCH_PRODUCTS,
  LOADING_PRODUCTS,
  SET_CURRENT_PRODUCT,
  FETCH_COMMENT,
  CREATE_COMMENT,
  FETCH_ADDRESS
};